name: LocalNR
version: "2.1.0"
license: "GPL-3.0-or-later"
date: 2026-05-22
description: |
    Package of local nearrings

authors:
    - name: Iryna Raievska
      url: https://www.imath.kiev.ua/~algebra/Raievska_I/
    - name: Maryna Raievska
      url: https://www.imath.kiev.ua/~algebra/Raievska_M/
    - name: Yaroslav Sysak
      url: https://www.imath.kiev.ua/~algebra/Sysak/

maintainers:
    - name: Iryna Raievska
      url: https://www.imath.kiev.ua/~algebra/Raievska_I/
    - name: Maryna Raievska
      url: https://www.imath.kiev.ua/~algebra/Raievska_M/

GAP: ">=4.10.0"

needed-pkgs:
    - name: "SONATA"
      version: ">= 2.4"
      url: "https://gap-packages.github.io/sonata/"

www: https://gap-packages.github.io/LocalNR
readme: README.md
packageinfo: https://gap-packages.github.io/LocalNR/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/LocalNR/releases/download/v2.1.0/LocalNR-2.1.0.tar.gz

abstract: |
    The <span class="pkgname">LocalNR</span> package contains the library of local nearrings of small orders and some functions to analyze finite nearrings.

status: other
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    local nearring, endomorphism, automorphisms group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>RRS26</span>]   <b class='BibAuthor'>Raievska, I., Raievska, M. and Sysak, Y.</b>,
     <i class='BibTitle'>LocalNR, Package of local nearrings,
             Version 2.1.0</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/LocalNR">https://gap-packages.github.io/LocalNR</a></span>.
    </p>
    

bibtex: |
    @misc{ LocalNR,
      author =           {Raievska, I. and Raievska, M. and Sysak, Y.},
      title =            {{LocalNR},  {Package  of  local  nearrings}, {V}ersion
                          2.1.0},
      month =            {May},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/LocalNR}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{LocalNR}}},
      keywords =         {local nearring; endomorphism; automorphisms group},
      printedkey =       {RRS26}
    }

